"""empty message

Revision ID: 1173d72e4d6
Revises: 41e43654661
Create Date: 2015-07-08 22:55:55.064849

"""

# revision identifiers, used by Alembic.
revision = '1173d72e4d6'
down_revision = '41e43654661'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
