"""empty message

Revision ID: 1fe85136437
Revises: 1173d72e4d6
Create Date: 2015-07-08 23:01:17.320189

"""

# revision identifiers, used by Alembic.
revision = '1fe85136437'
down_revision = '1173d72e4d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
