"""empty message

Revision ID: 40ea88d6877
Revises: 90df00843d
Create Date: 2015-07-08 23:07:50.266789

"""

# revision identifiers, used by Alembic.
revision = '40ea88d6877'
down_revision = '90df00843d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('smi', sa.Numeric(precision=5, scale=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'smi')
    ### end Alembic commands ###
